dlfiuhszdfjiknksjzdfkljnsdzjkfnlzdjshnfgkjnsdföglokijödkjfigjkvlkijhbsalöidughöoiauhsdfögoihjöiukjohö=1
print dlfiuhszdfjiknksjzdfkljnsdzjkfnlzdjshnfgkjnsdföglokijödkjfigjkvlkijhbsalöidughöoiauhsdfögoihjöiukjohö
